//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int MaSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> MaLop { get; set; }
    
        public virtual Diem Diem { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
